[package]
name = "jinshu"
description = "Merkle-backed storage engine and Noun graph database on NVMe"
keywords = ["jinshu", "storage", "merkle", "database"]
readme = "README.md"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.0"
[dependencies]
blake3 = { version = "1.8.7", default-features = false }
heapless = { version = "0.9.3", default-features = false }
kpack = "0.1.0"
noun = "0.1.0"
